docs/planejamento/Cronograma.md
Concluindo cronograma sugerido
=> versão final do cronograma planejado

docs/planejamento/RichPicture.md
Adição da bibliografia e correção do histórico de versões
=> Rich picture

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Criando templates para Issues e Pull requests
Adicionando com urgência os padrões para o repositório
Não houve testes.
=> Doc template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md
A master está na frente da dev novamente, portanto, precisamos atualizar a dev
=> Atualizando a Dev Novamente

docs/planejamento/metodologias.md
Em meio a construção do projeto precisa-se de uma metodologia para sermos mais eficiente dessa forma, foi criado um documento com essa informações a serem seguidas
Cria #37 
=> Metodologia

README.md, docs/atas/atas.md, docs/atas/reuniao01.md, docs/atas/reuniao02.md, docs/planejamento/Cronograma.md, docs/planejamento/Cronograma_realizado.md, docs/planejamento/Ferramentas.md, docs/planejamento/Lista_de_aplicativos.md, docs/planejamento/RichPicture.md, docs/planejamento/apresentacoes.md
O seguinte pull request tem como objetivo adicionar datas de revisão nos cronogramas de maneira correta, além de datas de revisão nos históricos de versão. Visando corrigir a issue #41.
Corrige #41
=> Atualização geral das datas de revisão

docs/elicitacao/introspeccao.md
Levantando requisitos utilizando a atecnica de introspecção
Corrige #66 
=> 66 introspecção

docs/elicitacao/analise-de-documentos.md
Levantamento dos requisitos utilizando análise de documentos.
Corrige #68 
=> 68 criar o artefato de análise de documentos

docs/elicitacao/introspeccao.md
Arrumando requisitos elicitados
Corrige #72 
=> Arrumar requisitos de introspecção #72

docs/planejamento/restricoes_de_uso.md
=> 40 criação do documento de restrição de uso

docs/elicitacao/storytelling.md
StoryTelling do projeto
Corrige #52 
Não houveram testes
=> 52 storytelling

docs/planejamento/app_selecionado.md, docs/planejamento/cronograma_realizado.md, docs/planejamento/lista_de_aplicativos.md
Adicionando artefato de App Selecionado
Corrige #63
=> docs: Criação do artefato App Selecionado #63

docs/_sidebar.md
Adicionando páginas na GitPage
Corrige #82
=> docs: Adicionando novas páginas na GitPage. #82

saida_de_membro.md
Documento indicando saída de membro
Corrige #87
=> Criação do documento saida de membro #87

docs/elicitacao/questionario.md
=> Justificando textos #91

docs/_sidebar.md, docs/home.md
=> #96 Atualizando a side bar

docs/planejamento/apresentacoes.md
=> #101 Arrumando link do ponto de controle 02

docs/planejamento/apresentacoes.md
=> #103 Adicionando revisor na apresentação

docs/_sidebar.md, docs/atas/_navbar.md, docs/atas/_sidebar.md, docs/atas/reuniao01.md, docs/atas/reuniao02.md, docs/atas/reuniao03.md, docs/atas/reuniao04.md, docs/atas/reuniao05.md
Padronização das atas e criação da 5ª ata.
Corrige # 113
=> 113 ata reunião 5

docs/modelagem/lexicos.md
=> 114 lexicos

docs/_sidebar.md, docs/atas/atas.md, docs/atas/reuniao05.md, docs/atas/reuniao06.md
Cria a ata da reunião 6.
Corrige #130
=> 130 criar ata

docs/modelagem/agil/historias_de_usuarios.md, docs/modelagem/lexicos.md
Artefato de Histórias de Usuários
Corrige #137
=> 137 historias de usuarios

docs/_sidebar.md
Atualizando gitpage.
Corrige #139
=> 139 atualizar gitpage

docs/modelagem/agil/backlog.md
=> 136 backlog

docs/verificacao/entrega_4/backlog_g4.md, docs/verificacao/entrega_4/historias_usuario_g4.md, docs/verificacao/entrega_4/nfr_framework_g4.md
Verificação da entrega 4 do grupo 4
Corrige #148
=> 148 verificar entrega 4 do grupo 4

docs/verificacao/verificacao_entrega_3/verificacao_casos-de-uso.md, docs/verificacao/verificacao_entrega_3/verificacao_cenarios.md, docs/verificacao/verificacao_entrega_3/verificacao_especificacao-suplementar.md, docs/verificacao/verificacao_entrega_3/verificacao_lexicos.md
Entrega verificação de requisitos etapa 3 do grupo 4.
Corrige #150
=> 150 verificacao entrega 3

docs/verificacao/verificacao_entrega_3/verificacao_casos-de-uso.md, docs/verificacao/verificacao_entrega_3/verificacao_cenarios.md, docs/verificacao/verificacao_entrega_3/verificacao_especificacao-suplementar.md, docs/verificacao/verificacao_entrega_3/verificacao_lexicos.md
=> Correcao bruno

docs/verificacao/entrega_4/backlog_g4.md, docs/verificacao/entrega_4/historias_usuario_g4.md, docs/verificacao/entrega_4/nfr_framework_g4.md
=> 158 arrumar verificação ponto de controle 4

docs/verificacao/entrega_4/backlog_g4.md
=> #158 Tentando arrumar gráfico

docs/verificacao/entrega_1/verificacao_aplicativos_escolhidos.md, docs/verificacao/entrega_1/verificacao_cronogramas.md, docs/verificacao/entrega_1/verificacao_ferramentas.md, docs/verificacao/entrega_1/verificacao_metodologias.md
Arrumado IDs nos artefatos em #163
=> #163 arrumado IDs

docs/validacao/prototipagem.md
=> 180 prototipacao

docs/entrega_final/resultados_alcancados.md
=> Igor missionista
